//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstraintToStudentTbl
    {
        public int ConsId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> PropId { get; set; }
        public Nullable<bool> Is { get; set; }
    
        public virtual PropertiesTbl PropertiesTbl { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
